---
- name: teardown
  hosts: localhost
  gather_facts: no

  tasks:
    - name: nginx down
      docker_compose:
        project_src: nginx
        state: absent

    - name: profana down
      docker_compose:
        project_src: profana
        state: absent

    - name: remove network
      docker_network:
        name: monitoring
        state: absent
