apiVersion: 1

deleteDatasources:
  - name: prometheus
    orgId: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: linode-swarm
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false