version: "3.9"

networks:
  web:
    driver: overlay

services:
  router:
    image: traefik:v2.4
    command: 
        - --api.insecure
        - --providers.docker
        - --providers.docker.swarmMode
        - --providers.docker.exposedByDefault=false
        - --entrypoints.http.address=:80
        - --entrypoints.https.address=:443
        - --entrypoints.http.http.redirections.entryPoint.scheme=https
        - --entrypoints.http.http.redirections.entryPoint.to=https
        - --entrypoints.http.http.redirections.entrypoint.permanent=true
        - --providers.file.directory=/etc/traefik/dynamic
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./certs:/etc/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs.yml:/etc/traefik/dynamic/certs.yaml
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - web