global:
  scrape_interval: 10s
  scrape_timeout: 8s

rule_files:
  - alerts.yml

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names: [ tasks.node-exporter ]
      port: 9100
      type: A

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names: [ tasks.cadvisor ]
      port: 8080
      type: A

  - job_name: 'docker-engine'
    dns_sd_configs:
    - names: [ tasks.engine-proxy ]
      port: 4998
      type: A
