version: '3.9'
networks:
  internal:
  monitoring:
    external: true
services:
  nginx:
    image: nginx
    volumes:
        - ./conf.d:/etc/nginx/conf.d
        - ./logs/:/var/log/nginx
    ports:
      - 8080:80
    networks:
      - internal
  nginx_exp:
    image: nginx/nginx-prometheus-exporter
    command: -nginx.scrape-uri=http://nginx/stub_status
    depends_on:
      - nginx
    networks:
      - internal
      - monitoring
