---
- hosts: all
  become: true
  vars_files:
      - vars.yml

  tasks:

    - name: allow swarm nodes
      iptables:
        chain: INPUT
        source: "{{item}}/32"
        jump: ACCEPT
      loop: "{{SWARM_ADDRS}}"

    - name: safe ip table config
      shell: iptables-save > /etc/iptables/rules.v4 && iptables-save > /etc/iptables/rules.v6

    - name: join to swarm
      docker_swarm:
        state: join
        join_token: "{{SWARM_TOKEN}}"
        remote_addrs: [ '{{COMMANDER_IP}}:2377' ]
        labels:
          linode_type: nanode
          project: playbox