---
- hosts: all
  become: true
  vars_files:
      - vars.yml

  pre_tasks:

    - name: update system
      apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

  tasks:

    - name: change default chain policy (used to clean rules)
      iptables:
        chain: INPUT
        policy: ACCEPT

    - name: Iptables flush tables
      iptables:
        table: '{{ item }}'
        flush: yes
      with_items:  [ 'nat', 'filter']

    - name: delete all user-defined chains on filter table
      shell: iptables -t filter -X

    - name: Allow packages to loopback interface
      iptables:
        in_interface: lo
        chain: INPUT
        jump: ACCEPT
        comment: loopback

    - name: Allow established & related state 
      iptables:
        chain: INPUT
        ctstate: [ RELATED, ESTABLISHED ]
        jump: ACCEPT

    - name: allow commander to connect on ssh
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: '22'
        ctstate: NEW
        jump: ACCEPT
        source: "{{COMMANDER_IP}}/32"
    
    - name: set input policy to drop
      iptables:
        chain: "INPUT"
        policy: DROP 
    
    - name: save iptables
      shell: iptables-save > /etc/iptables/rules.v4 && ip6tables-save > /etc/iptables/rules.v6

    - name: make sure sudo group exists
      group:
        name: sudo 
        state: present

    - name: Add sudo user user and add it to sudo
      user: 
        name: "{{SUDO_USER_NAME}}"
        password: "{{SUDO_USER_PWD}}"
        state: present
        createhome: yes
        groups: [ sudo ]
  
    - name: Set up authorized keys for the sudo user user
      authorized_key: 
        user: "{{SUDO_USER_NAME}}"
        key: "{{item}}"
      with_file:
        - ../secrets/playbox.pub

    - name: install fail2ban package
      apt: pkg=fail2ban state=present

    - name: copy fail2ban local config
      copy: 
        src: conf/jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: 0644
    
    - name: enable fail2ban
      service:
        name: fail2ban
        enabled: yes

    - name: install iptables-persistent
      apt: 
        pkg: iptables-persistent
        state: present

    - name: ssh config
      with_dict:
        LoginGraceTime: "1m"
        PermitRootLogin: "no"
        PubkeyAuthentication: "yes"
        PasswordAuthentication: "no"
        PermitEmptyPasswords: "no"
        IgnoreRhosts: "yes"
        Protocol: 2
        AllowUsers: "{{SUDO_USER_NAME}}"
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#?\s*{{item.key}}\s'
        line: '{{item.key}} {{item.value}}'
        state: present

    - name: enable sshd
      service:
        name: ssh
        enabled: yes

#  post_tasks:
#    
#    - name: reboot
#      reboot:
