{
 "title": "Docker Swarm",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum  (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1e9",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host Disc I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (device) (rate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Cluster Actions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(engine_daemon_container_actions_seconds_count[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[1m])) by (instance, name)",
     "legendFormat": " {{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "mb" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{id=~\"/docker/.*\"}) by (instance, container_label_com_docker_stack_namespace, name) / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container in Swarm",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (engine_daemon_container_states_containers)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}