version: '3.9'

networks:
  monitoring:
    driver: overlay
    attachable: true
  agent_network:
    driver: overlay
    attachable: true

volumes:
  prometheus-data:
  grafana-data:
  portainer-data:


services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    deploy:
      placement:
        constraints:
          - node.labels.prom==true
    
  dockerd-exporter:
    image: alpine/socat
    networks:
      - monitoring
    # change for address of docker0 and exposed metrics addr
    command: -d -d TCP-L:4999,fork TCP:172.17.0.1:4999
    deploy:
      mode: global

  node-exporter:
    image: quay.io/prometheus/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
    deploy:
      mode: global

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro 
    networks:
      - monitoring
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/var/grafana
    ports:
      - 3000:3000
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=super_secret"
      - "GF_USERS_ALLOW_SIGN_UP=false"
      - "GF_PATHS_PROVISIONING=/var/grafana/provisioning"
    networks:
      - monitoring
    deploy:
      placement:
        constraints:
          - node.labels.prom==true

  portainer_agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.portainer_agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer-data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]