version: '3.9'

networks:
  monitoring:
    driver: overlay

volumes:
  prometheus-data:
  grafana-data:

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    links:
      - node-exporter:node-exporter
    deploy:
      placement:
        constraints:
          - node.labels.prom==true
    
  engine-proxy:
    image: alpine/socat
    networks:
      - monitoring
    expose: 
      - "4998"
    command: -d -d TCP-L:4998,fork TCP:192.168.64.1:4999
    deploy:
      mode: global

  node-exporter:
    image: quay.io/prometheus/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
    deploy:
      mode: global

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro 
    networks:
      - monitoring
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/var/grafana
    ports:
      - 3000:3000
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=super_secret"
      - "GF_USERS_ALLOW_SIGN_UP=false"
      - "GF_PATHS_PROVISIONING=/var/grafana/provisioning"
    networks:
      - monitoring
    deploy:
      placement:
        constraints:
          - node.labels.prom==true
